#include <bits/stdc++.h>
using namespace std;struct P{double x,y;};struct Key{long long x,y;bool operator==(Key const&o)const{return x==o.x&&y==o.y;}};struct KH{size_t operator()(Key const&k)const{return hash<long long>()(k.x*1000003LL+k.y);}};Key key(P a){return{llround(a.x*1e8),llround(a.y*1e8)};}double ds(P a,P b){return hypot(a.x-b.x,a.y-b.y);}int main(int ac,char**av){if(ac<7){cerr<<"coords macro colors fixedmask out limit [seed]\n";return 2;}ifstream fc(av[1]),fm(av[2]),fco(av[3]),ffi(av[4]);ofstream out(av[5]);int LIMIT=stoi(av[6]);int n,m;fc>>n;vector<P>C(n);for(auto&p:C)fc>>p.x>>p.y;fm>>m;vector<P>M(m);for(auto&p:M)fm>>p.x>>p.y;vector<int>col(n),fixed(n);for(int&i:col)fco>>i;int x;while(ffi>>x)if(0<=x&&x<n)fixed[x]=1;unordered_map<Key,int,KH>idx;for(int i=0;i<n;i++)idx[key(C[i])]=i;double cell=1.05;unordered_map<long long,vector<int>>grid;auto gk=[&](int a,int b){return((long long)a<<32)^(unsigned)b;};for(int i=0;i<n;i++)if(fixed[i])grid[gk(floor(C[i].x/cell),floor(C[i].y/cell))].push_back(i);
map<long long,vector<pair<int,int>>>groups;vector<pair<int,int>>U;for(int i=0;i<m;i++)for(int j=i+1;j<m;j++){double d=ds(M[i],M[j]);groups[llround(d*1e8)].push_back({i,j});if(fabs(d-1)<3e-7)U.push_back({i,j});}
unordered_set<string>seen;long long trans=0,uniq=0;int killers=0;map<pair<int,int>,long long>hist;
auto incompatible=[&](vector<P>const&A,vector<int>const&old)->bool{
 vector<int>var(m,-1),vars;for(int i=0;i<m;i++)if(old[i]<0||!fixed[old[i]]){var[i]=vars.size();vars.push_back(i);}int q=vars.size();if(q==0){for(auto[i,j]:U)if(col[old[i]]==col[old[j]])return true;return false;}vector<int>mask(q,31);vector<vector<int>>adj(q);
 for(int aa=0;aa<q;aa++){int i=vars[aa];P z=A[i];int bx=floor(z.x/cell),by=floor(z.y/cell),forb=0;for(int dx=-1;dx<=1;dx++)for(int dy=-1;dy<=1;dy++){auto it=grid.find(gk(bx+dx,by+dy));if(it==grid.end())continue;for(int v:it->second)if(fabs(ds(z,C[v])-1)<3e-7)forb|=1<<col[v];}mask[aa]&=~forb;if(!mask[aa])return true;}
 for(auto[i,j]:U){int a=var[i],b=var[j];if(a>=0&&b>=0){adj[a].push_back(b);adj[b].push_back(a);}else if(a>=0){mask[a]&=~(1<<col[old[j]]);}else if(b>=0){mask[b]&=~(1<<col[old[i]]);}else if(col[old[i]]==col[old[j]])return true;}
 for(int a=0;a<q;a++)if(!mask[a])return true;vector<int>as(q,-1);function<bool(int)>dfs=[&](int left){if(!left)return true;int best=-1,bm=0,bc=99;for(int a=0;a<q;a++)if(as[a]<0){int mm=mask[a];for(int b:adj[a])if(as[b]>=0)mm&=~(1<<as[b]);int c=__builtin_popcount((unsigned)mm);if(c<bc){bc=c;best=a;bm=mm;if(c<=1)break;}}if(!bm)return false;while(bm){int bit=bm&-bm;bm-=bit;as[best]=__builtin_ctz((unsigned)bit);if(dfs(left-1))return true;as[best]=-1;}return false;};return !dfs(q);
};
vector<int> ord(n);iota(ord.begin(),ord.end(),0);uint64_t seed=(ac>=8?stoull(av[7]):1);mt19937_64 rg(seed);shuffle(ord.begin(),ord.end(),rg);for(int aa=0;aa<n;aa++)for(int bb=aa+1;bb<n;bb++){int u=ord[aa],v=ord[bb];long long dk=llround(ds(C[u],C[v])*1e8);auto git=groups.find(dk);if(git==groups.end())continue;for(auto[si,sj]:git->second)for(int rev=0;rev<2;rev++)for(int ref=0;ref<2;ref++){int tu=rev?v:u,tv=rev?u:v;double ax=M[sj].x-M[si].x,ay=M[sj].y-M[si].y;if(ref)ay=-ay;double bx=C[tv].x-C[tu].x,by=C[tv].y-C[tu].y,den=ax*ax+ay*ay,cr=(bx*ax+by*ay)/den,ci=(by*ax-bx*ay)/den;vector<P>A(m);vector<int>old(m,-1);string sig;int ov=0,fov=0;for(int k=0;k<m;k++){double xx=M[k].x-M[si].x,yy=M[k].y-M[si].y;if(ref)yy=-yy;A[k]={C[tu].x+cr*xx-ci*yy,C[tu].y+ci*xx+cr*yy};auto it=idx.find(key(A[k]));if(it!=idx.end()&&ds(A[k],C[it->second])<4e-7){old[k]=it->second;ov++;if(fixed[old[k]])fov++;}auto kk=key(A[k]);sig+=to_string(kk.x)+","+to_string(kk.y)+";";}trans++;if(fov<1)continue;if(!seen.insert(sig).second)continue;uniq++;hist[{ov,fov}]++;if(incompatible(A,old)){killers++;out<<"K "<<ov<<" "<<fov;for(auto p:A)out<<" "<<setprecision(17)<<p.x<<" "<<p.y;out<<"\n";out.flush();cerr<<"killer "<<killers<<" ov="<<ov<<" fov="<<fov<<" trans="<<trans<<" uniq="<<uniq<<"\n";if(killers>=LIMIT)goto done;}}}
done:cerr<<"done trans="<<trans<<" uniq="<<uniq<<" killers="<<killers<<"\n";for(auto[k,z]:hist)if(k.first>=8||k.second>=8)cerr<<"ov"<<k.first<<" f"<<k.second<<"="<<z<<" ";cerr<<"\n";}
