#include <bits/stdc++.h>
using namespace std;struct RNG{uint64_t s;RNG(uint64_t x):s(x){}uint64_t next(){s^=s<<7;s^=s>>9;s*=0x9e3779b97f4a7c15ULL;return s;}int ri(int n){return n?next()%n:0;}};
int main(int argc,char**argv){if(argc<8){cerr<<"graph k restarts iters seed seedcolors out\n";return 2;}string path=argv[1];int K=stoi(argv[2]),R=stoi(argv[3]);long long MAXIT=stoll(argv[4]);uint64_t seed=stoull(argv[5]);string seedp=argv[6],out=argv[7];
ifstream f(path);string s((istreambuf_iterator<char>(f)),{});auto cp=s.find("\"coords\""),ep=s.find("\"edges\"");int n=0,d=0;for(size_t i=s.find('[',cp);i<ep;i++){if(s[i]=='['){d++;if(d==2)n++;}else if(s[i]==']')d--;}vector<pair<int,int>>edges;d=0;vector<int>cur;for(size_t i=s.find('[',ep);i<s.size();i++){char c=s[i];if(c=='['){d++;if(d==2)cur.clear();}else if(isdigit(c)||c=='-'){size_t j=i+1;while(j<s.size()&&isdigit(s[j]))j++;cur.push_back(stoi(s.substr(i,j-i)));i=j-1;}else if(c==']'){if(d==2&&cur.size()>=2)edges.push_back({cur[0],cur[1]});d--;if(d==0)break;}}
vector<vector<int>>A(n);for(auto [u,v]:edges){A[u].push_back(v);A[v].push_back(u);}vector<int>comp(n,-1),sz;int cid=0,bestc=0;for(int st=0;st<n;st++)if(comp[st]<0){queue<int>q;q.push(st);comp[st]=cid;int z=0;while(!q.empty()){int v=q.front();q.pop();z++;for(int w:A[v])if(comp[w]<0)comp[w]=cid,q.push(w);}sz.push_back(z);if(z>sz[bestc])bestc=cid;cid++;}vector<int>old;for(int i=0;i<n;i++)if(comp[i]==bestc)old.push_back(i);vector<int>mp(n,-1);for(int i=0;i<(int)old.size();i++)mp[old[i]]=i;vector<vector<int>>adj(old.size());vector<pair<int,int>>E;for(int i=0;i<(int)old.size();i++)for(int w:A[old[i]])if(mp[w]>i){adj[i].push_back(mp[w]);adj[mp[w]].push_back(i);E.push_back({i,mp[w]});}vector<int>seedall(n);ifstream sf(seedp);for(int&i:seedall)sf>>i;n=old.size();cerr<<"n="<<n<<" m="<<E.size()<<" seedconf=";int sc=0;for(auto [u,v]:E)sc+=seedall[old[u]]==seedall[old[v]];cerr<<sc<<"\n";
atomic<bool>found(false);atomic<int>nextR(0);mutex mu;vector<int>answer;int bestGlobal=INT_MAX;auto worker=[&](int tid){while(!found){int rr=nextR.fetch_add(1);if(rr>=R)break;RNG rng(seed+rr*0x9e3779b97f4a7c15ULL+tid);vector<int>col(n);for(int i=0;i<n;i++)col[i]=seedall[old[i]];int perturb= rr==0?0:min(n/2, max(1,(rr%12+1)*n/100));for(int z=0;z<perturb;z++){int v=rng.ri(n);col[v]=rng.ri(K);}vector<array<int,8>>cnt(n);for(auto&x:cnt)x.fill(0);for(auto [u,v]:E){cnt[u][col[v]]++;cnt[v][col[u]]++;}int conflicts=0;for(auto [u,v]:E)conflicts+=col[u]==col[v];vector<int>cv,pos(n,-1);auto setconf=[&](int v){bool yes=cnt[v][col[v]]>0;if(yes&&pos[v]<0){pos[v]=cv.size();cv.push_back(v);}else if(!yes&&pos[v]>=0){int p=pos[v],w=cv.back();cv[p]=w;pos[w]=p;cv.pop_back();pos[v]=-1;}};for(int v=0;v<n;v++)setconf(v);vector<long long>tabu(n*K,0);int best=conflicts;long long stagnant=0;vector<pair<int,int>>moves;moves.reserve(n*K);
for(long long it=1;it<=MAXIT&&!found;it++){if(conflicts==0){lock_guard<mutex>lk(mu);if(!found){found=true;answer=col;cerr<<"FOUND r="<<rr<<" it="<<it<<"\n";}break;}int bd=INT_MAX;moves.clear();for(int v:cv){int oc=col[v];for(int nc=0;nc<K;nc++)if(nc!=oc){int dd=cnt[v][nc]-cnt[v][oc];bool asp=conflicts+dd<best;if(tabu[v*K+nc]>it&&!asp)continue;if(dd<bd){bd=dd;moves.clear();moves.push_back({v,nc});}else if(dd==bd)moves.push_back({v,nc});}}if(moves.empty()){fill(tabu.begin(),tabu.end(),0);continue;}auto [v,nc]=moves[rng.ri(moves.size())];int oc=col[v];vector<int>touch=adj[v];touch.push_back(v);conflicts+=cnt[v][nc]-cnt[v][oc];col[v]=nc;for(int w:adj[v]){cnt[w][oc]--;cnt[w][nc]++;}for(int w:touch)setconf(w);tabu[v*K+oc]=it+7+rng.ri(10)+(int)(0.5*conflicts);if(conflicts<best){best=conflicts;stagnant=0;int prev=bestGlobal;if(best<prev){lock_guard<mutex>lk(mu);if(best<bestGlobal){bestGlobal=best;cerr<<"best="<<best<<" r="<<rr<<" it="<<it<<"\n";}}}else stagnant++;if(stagnant>300000){for(int z=0;z<max(2,n/100);z++){int x=rng.ri(n),o=col[x],c=rng.ri(K);if(c==o)continue;vector<int>t=adj[x];t.push_back(x);conflicts+=cnt[x][c]-cnt[x][o];col[x]=c;for(int w:adj[x]){cnt[w][o]--;cnt[w][c]++;}for(int w:t)setconf(w);}fill(tabu.begin(),tabu.end(),0);stagnant=0;}}
}}
;vector<thread>ts;int T=max(1,min(R,(int)thread::hardware_concurrency()));for(int t=0;t<T;t++)ts.emplace_back(worker,t);for(auto&t:ts)t.join();if(!found){cerr<<"NO best="<<bestGlobal<<"\n";return 1;}ofstream fo(out);for(int i=0;i<n;i++)fo<<old[i]<<" "<<answer[i]<<"\n";return 0;}
